services:
  frontend:
    build:
      context: ./frontend
  echo:
    build:
      context: ./echo
  nginx:
    image: nginx
    ports:
      - 3000:80
    restart: "always"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

